# Generated by Django 3.2.4 on 2021-06-10 17:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windscreen', models.DecimalField(decimal_places=2, help_text='Windscreen addon price.', max_digits=10)),
                ('passanger_liability', models.DecimalField(decimal_places=2, help_text='Passanger liability addon price.', max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, help_text='Flood, Windstorm, Landslide or Subsidence addon price.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's name.", max_length=64)),
                ('email', models.EmailField(help_text="Customer's email.", max_length=254, unique=True)),
                ('mobile_number', models.CharField(help_text="Customer's mobile number.", max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_make', models.IntegerField(help_text='Vehicle year make.')),
                ('model', models.CharField(help_text='Vehicle model.', max_length=100)),
                ('number', models.CharField(help_text='Vehicle No.', max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=100000.0, help_text='Vehicle price in RM', max_digits=12, validators=[django.core.validators.MinValueValidator(30000.0)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Quotation number.', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Quotation price.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('windscreen', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Windscreen coverage', max_length=3)),
                ('passanger_liability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Passanger Liability coverage', max_length=3)),
                ('others', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Flood, Windstorm, Landslide or Subsidence coverage', max_length=3)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.vehicle')),
            ],
        ),
    ]
