# Generated by Django 3.2.4 on 2021-06-10 18:25

from django.db import migrations
from django.contrib.auth.models import User


def create_agent_account(apps, schema_editor):
    agent = User.objects.create(
        username='agent',
        is_staff=True,
        is_superuser=True
    )
    agent.set_password('agent')
    agent.save()


def create_add_on_price(apps, schema_editor):
    AddOnPrice = apps.get_model('quotations', 'AddOnPrice')
    AddOnPrice.objects.create(
        windscreen=500.00,
        passanger_liability=100.00,
        others=0.00
    )

class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_agent_account, migrations.RunPython.noop),
        migrations.RunPython(create_add_on_price, migrations.RunPython.noop)
    ]
