# Generated by Django 3.2.4 on 2021-06-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_create_agent_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='email',
            field=models.EmailField(help_text="Customer's email.", max_length=254),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='vehicle_number',
            field=models.CharField(help_text='Vehicle No.', max_length=20),
        ),
    ]
