# Generated by Django 3.2.4 on 2021-06-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_auto_20210612_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='cov_others',
            field=models.DecimalField(decimal_places=2, help_text='Flood, Windstorm, Landslide or Subsidence coverage.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='cov_passanger_liability',
            field=models.DecimalField(decimal_places=2, help_text='Passanger Liability coverage.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='cov_windscreen',
            field=models.DecimalField(decimal_places=2, help_text='Windscreen coverage.', max_digits=12, null=True),
        ),
    ]
